[program:socket]
command=node socket.js
directory=/var/www/src
autostart=true
autorestart=true
user=www-data
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stdout_logfile_backups=5
stdout_capture_maxbytes=10MB
stdout_events_enabled=true